#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tello-camera===final','console_scripts','tello_camera_contour'
__requires__ = 'tello-camera===final'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tello-camera===final', 'console_scripts', 'tello_camera_contour')()
    )
